# CMake generated Testfile for 
# Source directory: /home/andrei/Desktop/libdwarf-0.5.0/test
# Build directory: /home/andrei/Desktop/libdwarf-0.5.0/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(selfteststring "/home/andrei/Desktop/libdwarf-0.5.0/test/selfteststring")
set_tests_properties(selfteststring PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;11;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftestextrastring "/home/andrei/Desktop/libdwarf-0.5.0/test/selftestextrastring")
set_tests_properties(selftestextrastring PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;26;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftest_linkedtopath "/home/andrei/Desktop/libdwarf-0.5.0/test/selftest_linkedtopath")
set_tests_properties(selftest_linkedtopath PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;46;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfgetopttest "/home/andrei/Desktop/libdwarf-0.5.0/test/selfgetopttest")
set_tests_properties(selfgetopttest PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;60;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfmakename "/home/andrei/Desktop/libdwarf-0.5.0/test/selfmakename")
set_tests_properties(selfmakename PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;77;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfhelpertree "/home/andrei/Desktop/libdwarf-0.5.0/test/selfhelpertree")
set_tests_properties(selfhelpertree PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;92;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfmacrocheck "/home/andrei/Desktop/libdwarf-0.5.0/test/selfmacrocheck")
set_tests_properties(selfmacrocheck PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;109;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftestesb "/home/andrei/Desktop/libdwarf-0.5.0/test/selftestesb")
set_tests_properties(selftestesb PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;125;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftestsanitized "/home/andrei/Desktop/libdwarf-0.5.0/test/selftestesb")
set_tests_properties(selftestsanitized PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;140;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfsectionbitmaps "/home/andrei/Desktop/libdwarf-0.5.0/test/selfsectionbitmaps")
set_tests_properties(selfsectionbitmaps PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;154;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfleb "/home/andrei/Desktop/libdwarf-0.5.0/test/selfleb")
set_tests_properties(selfleb PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;165;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftied "/home/andrei/Desktop/libdwarf-0.5.0/test/selftied")
set_tests_properties(selftied PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;177;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selftestnames "/home/andrei/Desktop/libdwarf-0.5.0/test/selftestnames")
set_tests_properties(selftestnames PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;187;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfjitreader "sh" "-c" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_jitreaderdiff.sh /home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfjitreader PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;192;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selferrmsglist "/home/andrei/Desktop/libdwarf-0.5.0/test/selferrmsglist" "-f" "/home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selferrmsglist PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;203;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfcanonical "/home/andrei/Desktop/libdwarf-0.5.0/test/selfcanonical")
set_tests_properties(selfcanonical PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;219;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfteststrcpy "/home/andrei/Desktop/libdwarf-0.5.0/test/selfteststrcpy")
set_tests_properties(selfteststrcpy PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;231;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfregex "/home/andrei/Desktop/libdwarf-0.5.0/test/selfregex")
set_tests_properties(selfregex PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;244;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfdwarfdumppe "python3" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_dwarfdump.py" "PE" "cmake" "/home/andrei/Desktop/libdwarf-0.5.0" "/home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfdwarfdumppe PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;259;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfdwarfdumpelf "python3" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_dwarfdump.py" "Elf" "cmake" "/home/andrei/Desktop/libdwarf-0.5.0" "/home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfdwarfdumpelf PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;266;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfdwarfdumpmacho "python3" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_dwarfdump.py" "Macos" "cmake" "/home/andrei/Desktop/libdwarf-0.5.0" "/home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfdwarfdumpmacho PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;273;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfdebuglinka "sh" "-c" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_debuglink-a.sh /home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfdebuglinka PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;279;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
add_test(selfdebuglinkb "sh" "-c" "/home/andrei/Desktop/libdwarf-0.5.0/test/test_debuglink-b.sh /home/andrei/Desktop/libdwarf-0.5.0")
set_tests_properties(selfdebuglinkb PROPERTIES  _BACKTRACE_TRIPLES "/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;285;add_test;/home/andrei/Desktop/libdwarf-0.5.0/test/CMakeLists.txt;0;")
